export const etfVsObbligazioniContent = [
  { type: 'p', text: "La domanda più comune di chi inizia a investire è: \"meglio azioni o obbligazioni?\" La risposta è quasi sempre: entrambe, nella proporzione giusta per te. Ma per capire perché, bisogna prima capire la differenza." },
  { type: 'h2', text: 'Il confronto diretto' },
  {
    type: 'table',
    headers: ['', 'ETF Azionari', 'ETF Obbligazionari'],
    rows: [
      ['Rischio', 'Alto', 'Basso-Medio'],
      ['Rendimento atteso', '6\u201310% annuo', '1\u20134% annuo'],
      ['Volatilità annua', 'Alta (±20\u201340%)', 'Bassa (±3\u20138%)'],
      ['Orizzonte consigliato', '10+ anni', '2\u20137 anni'],
      ['In caso di crisi', 'Possibili cali del −30/50%', 'Relativa stabilità'],
      ['Cosa ottieni', 'Crescita del capitale nel tempo', 'Cedole + protezione capitale'],
    ],
  },
  { type: 'h2', text: 'Quando convengono gli ETF azionari' },
  { type: 'p', text: "Gli ETF azionari sono l'ingrediente principale per far crescere il capitale nel lungo periodo. Se hai un orizzonte di 10, 20 o 30 anni, le fluttuazioni di breve termine non contano: quello che conta è che storicamente i mercati azionari globali hanno sempre recuperato i cali e raggiunto nuovi massimi." },
  { type: 'p', text: "Sono la scelta giusta se: hai tempo davanti, non hai bisogno di quei soldi nel breve periodo, e riesci a resistere alla tentazione di vendere durante i momenti di panico (che arriveranno, è garantito)." },
  { type: 'h2', text: 'Quando convengono gli ETF obbligazionari' },
  { type: 'p', text: "Gli ETF obbligazionari entrano in gioco quando vuoi proteggere il capitale già accumulato, o quando il tuo orizzonte temporale si accorcia. Non sono il modo per fare soldi velocemente, ma per preservare quelli che hai già guadagnato." },
  { type: 'p', text: "Sono adatti se: ti stai avvicinando all'obiettivo (es. pensione tra 5 anni), vuoi un portafoglio con meno volatilità, o hai già accumulato molto e non vuoi rischiare di perderlo in un anno di crisi." },
  { type: 'h2', text: 'Perché un portafoglio usa entrambi' },
  { type: 'p', text: "Un portafoglio con solo azioni può perdere il 40\u201350% in un anno di crisi grave. Per molte persone, vedere quella perdita porta a vendere tutto nel momento peggiore — cristallizzando le perdite e perdendo il successivo recupero." },
  { type: 'p', text: "Aggiungere obbligazioni riduce la volatilità complessiva. Un portafoglio 70% azioni + 30% obbligazioni storicamente perde meno durante le crisi, ed è molto più facile da mantenere psicologicamente." },
  { type: 'box', variant: 'info', title: 'Il paradosso della diversificazione', text: "Un portafoglio misto azioni+obbligazioni non ha necessariamente rendimenti peggiori di uno 100% azionario nel lungo periodo. La ragione è comportamentale: il portafoglio misto è più facile da mantenere durante le crisi, evitando le vendite in perdita che distruggono il rendimento reale. Chi vende al −30% non partecipa al +50% successivo." },
  { type: 'h2', text: 'I 4 profili del simulatore' },
  { type: 'p', text: "PianoFinanziario usa 4 profili di investimento, ciascuno con una diversa esposizione al rischio:" },
  {
    type: 'table',
    headers: ['Profilo', 'Rischio', 'Orientamento', 'Rendimento atteso'],
    rows: [
      ['Crescita', 'Alto', 'Massimizza il rendimento', '9,5%'],
      ['Bilanciato', 'Medio-alto', 'Crescita con protezione', '7,5%'],
      ['Dormiglione', 'Medio', 'Semplicità massima', '6,5%'],
      ['Prudente', 'Basso', 'Stabilità prima di tutto', '5,5%'],
    ],
  },
  { type: 'box', variant: 'example', title: 'Quale profilo fa per te?', text: "Non esiste il profilo \"migliore\" in assoluto — esiste quello più adatto alla tua situazione. Se hai 25 anni e un lavoro stabile, puoi permetterti più rischio azionario. Se hai 55 anni e vuoi andare in pensione tra 10 anni, probabilmente vuoi più stabilità. Il simulatore ti aiuta a capirlo rispondendo a 6 domande." },
]
