import { etfContent } from './etf'
import { obbligazioniContent } from './obbligazioni'
import { etfVsObbligazioniContent } from './etfVsObbligazioni'

export const ARTICLES = [
  {
    slug: 'cosa-sono-gli-etf',
    title: 'Cosa sono gli ETF',
    description: 'Il mattone base di ogni piano di investimento moderno: come funzionano e perché costano così poco.',
    readTime: '5 min',
    icon: '📦',
    category: 'Fondamentali',
    badge: 'Inizia da qui',
    metaDescription: 'Scopri cosa sono gli ETF, come funzionano e perché sono lo strumento ideale per investire in modo semplice ed economico.',
    next: 'cosa-sono-le-obbligazioni',
    available: true,
    content: etfContent,
  },
  {
    slug: 'cosa-sono-le-obbligazioni',
    title: 'Cosa sono le obbligazioni',
    description: 'Come funziona il lato "sicuro" di un portafoglio: rendimento stabile, rischio basso, ruolo essenziale.',
    readTime: '4 min',
    icon: '🏦',
    category: 'Fondamentali',
    badge: null,
    metaDescription: 'Scopri cosa sono le obbligazioni, perché sono più sicure delle azioni e qual è il loro ruolo in un portafoglio bilanciato.',
    next: 'etf-vs-obbligazioni',
    available: true,
    content: obbligazioniContent,
  },
  {
    slug: 'etf-vs-obbligazioni',
    title: 'ETF azionari vs obbligazionari: qual è la differenza?',
    description: 'Rischio, rendimento, orizzonte temporale: tutto quello che serve per capire come combinarli.',
    readTime: '5 min',
    icon: '⚖️',
    category: 'Fondamentali',
    badge: null,
    metaDescription: 'Confronto tra ETF azionari e obbligazionari: rischio, rendimento atteso, orizzonte consigliato e come usarli insieme in un portafoglio.',
    next: 'cosa-e-il-pac',
    available: true,
    content: etfVsObbligazioniContent,
  },
  {
    slug: 'cosa-e-il-pac',
    title: "Cos'è il PAC (Piano di Accumulo del Capitale)",
    description: 'Investire una cifra fissa ogni mese, automaticamente. Perché funziona meglio del "aspetto il momento giusto".',
    readTime: '5 min',
    icon: '📅',
    category: 'Strategie',
    badge: null,
    metaDescription: "Cos'è il PAC, come funziona il dollar cost averaging e perché investire €50/mese è meglio di non fare nulla.",
    next: 'interesse-composto',
    available: false,
    content: [],
  },
  {
    slug: 'interesse-composto',
    title: "L'interesse composto: l'ottava meraviglia del mondo",
    description: 'Perché Einstein lo chiamava così e come può trasformare piccoli versamenti mensili in un patrimonio.',
    readTime: '4 min',
    icon: '📈',
    category: 'Fondamentali',
    badge: null,
    metaDescription: "Scopri l'interesse composto con esempi numerici semplici: la regola del 72, il potere del tempo e perché iniziare prima fa una differenza enorme.",
    next: 'come-scegliere-un-broker',
    available: false,
    content: [],
  },
  {
    slug: 'come-scegliere-un-broker',
    title: 'Come scegliere un broker per comprare ETF in Italia',
    description: "Fineco, Scalable Capital, Trade Republic, DEGIRO, IBKR: confronto commissioni, facilità d'uso e regime fiscale.",
    readTime: '6 min',
    icon: '🏙️',
    category: 'Pratica',
    badge: null,
    metaDescription: 'Guida alla scelta del broker per ETF in Italia: confronto tra Fineco, Scalable Capital, Trade Republic, DEGIRO e Interactive Brokers.',
    next: 'come-ribilanciare',
    available: false,
    content: [],
  },
  {
    slug: 'come-ribilanciare',
    title: "Cos'è il ribilanciamento e quando farlo",
    description: 'Come mantenere le proporzioni del portafoglio nel tempo, senza vendere e pagare troppe tasse.',
    readTime: '5 min',
    icon: '🔄',
    category: 'Pratica',
    badge: null,
    metaDescription: "Guida al ribilanciamento del portafoglio ETF: quando farlo, come usare i nuovi versamenti e l'impatto fiscale delle vendite.",
    next: 'tasse-etf-italia',
    available: false,
    content: [],
  },
  {
    slug: 'tasse-etf-italia',
    title: 'Le tasse sugli ETF in Italia',
    description: 'Aliquota 26%, accumulo vs distribuzione, broker italiano vs estero: tutto quello che devi sapere.',
    readTime: '6 min',
    icon: '📋',
    category: 'Fiscale',
    badge: null,
    metaDescription: 'Come funzionano le tasse sugli ETF in Italia: aliquota 26%, differenza tra accumulo e distribuzione, broker italiano vs estero.',
    next: null,
    available: false,
    content: [],
  },
]

export function getArticle(slug) {
  return ARTICLES.find(a => a.slug === slug) || null
}
