export const interesseCompostoContent = [
  { type: 'p', text: "L'interesse composto è il meccanismo per cui i tuoi guadagni generano altri guadagni. Non guadagni solo sul capitale iniziale, ma anche su tutto quello che hai già guadagnato. Nel tempo, questo crea una crescita esponenziale — non lineare." },
  { type: 'p', text: 'Einstein lo avrebbe definito "l\'ottava meraviglia del mondo". Che lo abbia detto davvero o no, il concetto è reale: con abbastanza tempo, anche piccole somme diventano grandi.' },
  { type: 'h2', text: 'Interesse semplice vs interesse composto' },
  { type: 'p', text: "Con interesse semplice, guadagni sempre la stessa percentuale sul capitale iniziale. Con \u20ac10.000 al 7%, guadagni \u20ac700 ogni anno — sempre \u20ac700, ogni anno, per sempre." },
  { type: 'p', text: "Con interesse composto, il rendimento del primo anno si aggiunge al capitale e genera rendimento anche lui l'anno dopo. \u20ac10.000 \u2192 \u20ac10.700 \u2192 \u20ac11.449 \u2192 \u20ac12.250... ogni anno la base su cui calcoli il 7% è più grande." },
  { type: 'box', variant: 'info', title: 'I numeri dopo 30 anni', text: "\u20ac10.000 al 7% annuo con interesse semplice \u2192 \u20ac31.000. Con interesse composto \u2192 \u20ac76.123. La differenza è \u20ac45.000 — generati solo dal reinvestimento dei guadagni, senza versare un euro in più." },
  { type: 'h2', text: 'La regola del 72' },
  { type: 'p', text: "Vuoi sapere in quanti anni raddoppia il tuo investimento? Dividi 72 per il tasso di rendimento annuo. Con un rendimento del 7%, il capitale raddoppia ogni 72\u00f77 \u2248 10 anni." },
  { type: 'box', variant: 'example', title: 'Raddoppi in cascata', text: "Investi \u20ac10.000 a 25 anni, con rendimento medio 7%: a 35 anni hai \u20ac20.000 \u2192 a 45 anni \u20ac40.000 \u2192 a 55 anni \u20ac80.000 \u2192 a 65 anni \u20ac160.000. Senza versare un euro in più. Il tempo ha moltiplicato il capitale per 16." },
  { type: 'h2', text: 'Perché iniziare presto è la mossa più importante' },
  { type: 'p', text: "Il tempo è l'ingrediente che non puoi comprare o recuperare. Chi inizia 10 anni prima ottiene risultati che chi inizia dopo non può raggiungere nemmeno investendo molto di più." },
  { type: 'box', variant: 'info', title: 'Marco vs Luca', text: "Marco investe \u20ac200/mese dai 25 ai 35 anni (10 anni, \u20ac24.000 totali), poi smette. Luca inizia a 35 anni e investe \u20ac200/mese fino a 65 anni (30 anni, \u20ac72.000 totali). A 65 anni, con rendimento 7%: Marco ha \u20ac263.000, Luca \u20ac243.000. Chi ha investito 3 volte meno ha di più, grazie ai 10 anni di vantaggio." },
  { type: 'p', text: "La lezione: il momento migliore per iniziare era 10 anni fa. Il secondo momento migliore è oggi." },
]
